#!/bin/sh

# OpenRC boots with standard inittab
# Bill Wang <freecnpro@gmail.com>

### BEGIN INIT INFO
# Provides:          /etc/init.d/rcS
# Required-Start:    
# Required-Stop:     
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     
# Default-Stop:      
# Short-Description: This is a false service.
# Description:       This is a false service, OpenRC boots with standard inittab.
### END INIT INFO

set -e

exec /sbin/rc sysinit
